config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: 'home#index'

  devise_for :users, controllers: { sessions: 'users/sessions' }

  devise_scope :user do
    authenticated :user do
      root to: "devise/sessions#new"
    end
    unauthenticated do
      root to: 'home#customer'
    end
    get "/sign_out", to: "sessions#destroy"
    get "/forgot_password", to: "sessions#forgot_password"
    put "/reset", to: "sessions#reset_password"
    get "/check_username_exists", to: "sessions#check_username_exists"
  end

  resources :home do
    collection do
      get :download_pdf
    end
  end

  resources :users, controller: :users do
    collection do
      put :update_profile
      get :edit_profile
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :portfolios
  has_attached_file :avatar, styles: { medium: "300x300>", thumb:  "100x100>", tiny: '32x32>' }, default_url: "user/default_image.png"

  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  process_in_background :avatar, processing_image_url: "/assets/about.jpg"

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  # DELETE /resource/sign_out
  layout 'login'
  def new
    super
  end
  # def edit
  #   super
  # end
  def destroy
    signed_out = (Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name))
    yield if block_given?
    redirect_to root_path
  end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def update_profile
    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end
    current_user.update_attributes(profile_params)

    if @current_user.errors.empty?
      redirect_to root_path, notice: I18n.t("common.update_users_success")
    else
      render :edit_profile
    end

  end

  private

  def profile_params
    params.require(:user).permit(:email, :password, :password_confirmation, :avatar)
  end
end

app/views/users/_update_profile_form.html.slim
/ - if user.new_record?
/   - btn_string = t('common.add')
/ - else
/   - btn_string = t('common.save_change')
= form_for user, url: update_profile_users_path, id: 'user-form', html: {method: :put, multipart: true, class: 'form-horizontal user-form'} do |f|

  #user-form.block-content
    .row
      .col-md-4
        .form-group
          = f.label :email
            = t('.email')
            span.f_req *
          = f.text_field :email, readonly:true, class: 'form-control'
        .form-group
          = f.label :password
            = t('.password')
            span.f_req *
          = f.password_field :password, class: 'form-control'
        .form-group
          = f.label :password_confirmation
            = t('.password_confirmation')
            span.f_req *
          = f.password_field :password_confirmation, class: 'form-control'
        .input-image
          #target
            = image_tag current_user.avatar.url
          #input-file
            = f.file_field :avatar, id: 'pictureInput'

      / .col-md-4.col-md-offset-1.right-block
      /   .form-group
      /     = f.label :first_name
      /       = t('.first_name')
      /       span.f_req
      /     = f.text_field :first_name, class: 'form-control'
      /   .form-group
      /     = f.label :last_name
      /       = t('.last_name')
      /       span.f_req
      /     = f.text_field :last_name, class: 'form-control'
      /   .form-group
      /     = f.label :mobile
      /       = t('.mobile')
      /       span.f_req
      /     = f.text_field :mobile, class: 'form-control'
    .row.top-space
      .col-md-4
        .form-group
          = f.submit "Update",  class: 'btn btn-success update'
          = link_to root_path, class: 'cancel'
            .btn.btn-danger
              |Cancel
javascript:
  $('#input-file #pictureInput').on('change', function(event) {
    var files, image, reader;
    files = event.target.files;
    image = files[0];
    console.log(image.size);
    reader = new FileReader;
    reader.onload = function(file) {
      var img;
      img = new Image;
      console.log(file);
      img.src = file.target.result;
      $('#target').html(img);
      console.log('minh hai');
    };
    reader.readAsDataURL(image);
  });

app/views/users/edit_profile.html.slim
#editUser-form.user-form
  .row
    .col-md-10
      = render 'update_profile_form', user: current_user