config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: 'home#index'

  devise_for :users, controllers: { sessions: 'users/sessions' }

  devise_scope :user do
    authenticated :user do
      root to: "devise/sessions#new"
    end
    unauthenticated do
      root to: 'home#customer'
    end
    get "/sign_out", to: "sessions#destroy"
    get "/forgot_password", to: "sessions#forgot_password"
    put "/reset", to: "sessions#reset_password"
    get "/check_username_exists", to: "sessions#check_username_exists"
  end

  resources :home do
    collection do
      get :download_pdf
    end
  end

  resources :users, controller: :users do
    collection do
      put :update_profile
      get :edit_profile
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @portfolios = Portfolio.all
    @banner_images = Banner.first
  end
  def download_pdf
    file_path = "#{Rails.root}/public/camera.pdf"
    send_file file_path, filename: "camera.pdf", type: 'application/pdf', disposition: 'inline'
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_about.html.slim
/ tinymce
= tinymce_assets
= tinymce
/! About Section
#about
  .container
    .section-title.text-center.center
      h2 GIỚI THIỆU
      hr/
    .row
      .col-md-12.text-center
        = image_tag "about.jpg", class: "img-responsive"

      .col-md-8.col-md-offset-2
        .about-text
          h3 THÀNH LẬP:
          p Công Ty TNHH Công Nghệ Viễn Thông MiHa được thành lập theo quyết định số 0317856979 do Sở Kế hoạch và Đầu tư Thành phố Hồ Chí Minh cấp, với lĩnh vực phân phối các sản phẩm viễn thông, và các gói giải pháp tổng thể về viễn thông cho khách hàng.
          p Với 8 năm hoạt động trong ngành, đặc biệt là lĩnh vực camera quan sát. MiHa đã gặt hái được nhiều thành công và tạo dựng được lòng tin tưởng tuyệt đối với nhiều khách hàng trong cả nước.

          h3 CÁC LĨNH VỰC PHÁT TRIỂN:
          p - Cung cấp vật tư, thiết bị và giải pháp toàn diện trong lĩnh vực Viễn thông.
          p - Hỗ trợ kỹ thuật, thực hiện các dịch vụ bảo hành – sửa chữa hệ thống tổng đài & hệ thống camera quan sát.
          p - Tư vấn lắp đặt, thiết kế và thi công hoàn chỉnh các hệ thống an ninh mạng Viễn thông.
          p - Bảo trì, bảo dưỡng hệ thống tổng đài điện thoại, báo trộm - báo cháy, camera quan sát, máy chấm công... và các thiết bị văn phòng khác.

          = text_area_tag :content, "", :class => "tinymce", :rows => 10, :cols => 80
          p.text-center
            a.btn.btn-primary href="#"
              i.fa.fa-download
              | Download Resume

app/views/home/_achievements.html.slim
/! Achievements Section
#achievements.text-center
  .container
    .section-title.center
      h2 KHÁCH HÀNG NÓI GÌ VỀ CHÚNG TÔI
      h3 SỰ THÀNH CÔNG CỦA KHÁCH HÀNG LÀ MỤC TIÊU CỦA CHÚNG TÔI
      hr/
    .row
      .col-md-3.col-sm-3.wow.fadeInDown data-wow-delay="200ms"
        .achievement-box
          span.count 310
          h4 HAPPY CLIENTS
      .col-md-3.col-sm-3.wow.fadeInDown data-wow-delay="400ms"
        .achievement-box
          span.count 4700
          h4 HOURS OF WORK
      .col-md-3.col-sm-3.wow.fadeInDown data-wow-delay="600ms"
        .achievement-box
          span.count 30
          h4 PROJECT
      .col-md-3.col-sm-3.wow.fadeInDown data-wow-delay="800ms"
        .achievement-box
          span.count 8
          h4 YEAR OF EXPERIENCE

app/views/home/_banner.html.slim
/! Header
header#banner
  .container
    .intro
      .w3-content.w3-display-container
        = image_tag banner_images.image1.url(:large), class: "mySlides w3-animate-fading"
        = image_tag banner_images.image2.url(:large), class: "mySlides w3-animate-fading"
        = image_tag banner_images.image3.url(:large), class: "mySlides w3-animate-fading"
        // manual translation
        .w3-center.w3-container.w3-section.w3-large.w3-text-red.w3-display-bottommiddle style="width:100%"
          .w3-left.w3-hover-text-khaki onclick="plusDivs(-1)"
            .fa.fa-angle-left
          .w3-right.w3-hover-text-khaki onclick="plusDivs(1)"
            .fa.fa-angle-right
        .circle-selected
          span.w3-badge.demo.w3-border.w3-transparent.w3-hover-white onclick="currentDiv(1)"
          span.w3-badge.demo.w3-border.w3-transparent.w3-hover-white onclick="currentDiv(2)"
          span.w3-badge.demo.w3-border.w3-transparent.w3-hover-white onclick="currentDiv(3)"

javascript:
  // manual translation
  var slideIndex = 1;
  showDivs(slideIndex);

  function plusDivs(n) {
    showDivs(slideIndex += n);
  }

  function currentDiv(n) {
    showDivs(slideIndex = n);
  }

  function showDivs(n) {
    var i;
    var x = document.getElementsByClassName("mySlides");
    var dots = document.getElementsByClassName("demo");
    if (n > x.length) {slideIndex = 1}
    if (n < 1) {slideIndex = x.length}
    for (i = 0; i < x.length; i++) {
       x[i].style.display = "none";
    }
    for (i = 0; i < dots.length; i++) {
       dots[i].className = dots[i].className.replace(" blue-icon", "");
    }
    x[slideIndex-1].style.display = "block";
    dots[slideIndex-1].className += " blue-icon";
  }

  // auto translation
  // var myIndex = 0;
  // carousel();

  // function carousel() {
  //   var i;
  //   var x = document.getElementsByClassName("mySlides");
  //   for (i = 0; i < x.length; i++) {
  //      x[i].style.display = "none";
  //   }
  //   myIndex++;
  //   if (myIndex > x.length) {myIndex = 1}
  //   x[myIndex-1].style.display = "block";
  //   setTimeout(carousel, 3000);
  // }

app/views/home/_company_position_js.html.erb
<script type="text/javascript">
  Position.buildMapFromMarkerHash("company-position-map", 17, <%=raw hash.to_json %>);


  // var handler;

  // handler = Gmaps.build('Google');

  // handler.buildMap({
  //   provider: {},
  //   internal: {
  //     id: 'company-position-map'
  //   }
  // }, function() {
  //   var markers;
  //   markers = handler.addMarkers(<%=raw hash.to_json %>);
  //   handler.bounds.extendWith(markers);
  //   handler.fitMapToBounds();
  //   window.map = handler.getMap();
  //   return map.setZoom(17);
  // });
</script>

app/views/home/_contact.html.slim
/! Contact Section
#contact.text-center
  .container
    .section-title.center
      h2 LIÊN HỆ
      hr/
    .col-md-8.col-md-offset-2
      .col-md-4
        i.fa.fa-map-marker.fa-2x
        p
          | 443/86 Lê Văn Sỹ
          br
          | Phường 12, Quận 3
          br
          | Tp. Hồ Chí Minh.
      .col-md-4
        i.fa.fa-envelope-o.fa-2x
        p info@miha.com.vn
      .col-md-4
        i.fa.fa-phone.fa-2x
        p +918 657 600
      .clearfix
    .col-md-8.col-md-offset-2
      h3 Để lại lời nhắn.
      form#contactForm name="sentMessage" novalidate=""
        .row
          .col-md-6
            .form-group
              input#name.form-control placeholder="Name" required="required" type="text" /
              p.help-block.text-danger
          .col-md-6
            .form-group
              input#email.form-control placeholder="Email" required="required" type="email" /
              p.help-block.text-danger
        .form-group
          textarea#message.form-control name="message" placeholder="Message" required="" rows="4"
          p.help-block.text-danger
        #success
        button.btn.btn-default type="submit"  Gửi tin nhắn.
      .social
        ul
          li
            a href="#"
              i.fa.fa-facebook
          li
            a href="#"
              i.fa.fa-twitter
          li
            a href="#"
              i.fa.fa-dribbble
          li
            a href="#"
              i.fa.fa-github
          li
            a href="#"
              i.fa.fa-instagram
          li
            a href="#"
              i.fa.fa-linkedin

    .col-md-8.col-md-offset-2
      div style="width: 800px;"
        #company-position-map style="width: 800px; height: 400px;"

= render 'company_position_js', hash: hash

app/views/home/_experience.html.slim
/! Resume Section
#resume.text-center
  .container
    .section-title.center
      h2 Experience
      hr/
    .row
      .col-lg-12
        ul.timeline
          li
            .timeline-image
              h4
                | Feb 2013
                br/
                | \-
                br/
                | Present
            .timeline-panel
              .timeline-heading
                h4 Creative Agency
                h4.subheading UX Developer
              .timeline-body
                p Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sed dapibus leo nec ornare diamcommodo nibh ante facilisis.
          li.timeline-inverted
            .timeline-image
              h4
                | Nov 2011
                br/
                | \-
                br/
                | Jan 2013
            .timeline-panel
              .timeline-heading
                h4 Creative Agency
                h4.subheading Front-end Developer
              .timeline-body
                p Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sed dapibus leo nec ornare diamcommodo nibh ante facilisis.
          li
            .timeline-image
              h4
                | Dec 2009
                br/
                | \-
                br/
                | May 2011
            .timeline-panel
              .timeline-heading
                h4 Creative Agency
                h4.subheading UX Designer
              .timeline-body
                p Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sed dapibus leo nec ornare diamcommodo nibh ante facilisis.
  .container
    .section-title.center
      h2 Education
      hr/
    .row
      .col-lg-12
        ul.timeline
          /! Education Section
          li
            .timeline-image
              h4
                | 2010
                br/
                | \-
                br/
                | 2011
            .timeline-panel
              .timeline-heading
                h4 Design University
                h4.subheading Master Degree of Design
              .timeline-body
                p Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sed dapibus leo nec ornare diamcommodo nibh ante facilisis.
          li.timeline-inverted
            .timeline-image
              h4
                | 2007
                br/
                | \-
                br/
                | 2010
            .timeline-panel
              .timeline-heading
                h4 Design University
                h4.subheading Bachelor Degree of Design
              .timeline-body
                p Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sed dapibus leo nec ornare diamcommodo nibh ante facilisis.
          li
            .timeline-image
              h4
                | 2004
                br/
                | \-
                br/
                | 2007
            .timeline-panel
              .timeline-heading
                h4 School Name
                h4.subheading High School Degree
              .timeline-body
                p.text-muted Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sed dapibus leo nec ornare diamcommodo nibh ante facilisis.

app/views/home/_nav_bar.html.slim
/! Navigation
#nav
  nav.navbar.navbar-custom
    .container
      .navbar-header
        / responsive
        button.navbar-toggle data-target=".navbar-main-collapse" data-toggle="collapse" type="button"
          i.fa.fa-bars
        /logo
        .logo-and-name
          .logo
            = image_tag "logo_miha_2.png", class: "logo-icon img-responsive"
          .name
            a.navbar-brand.page-scroll href="#page-top" MiHa Tech Solutions
      /! Collect the nav links, forms, and other content for toggling
      .collapse.navbar-collapse.navbar-right.navbar-main-collapse
        ul.nav.navbar-nav
          /! Hidden li included to remove active class from about link when scrolled up past about section
          li.hidden
            a href="#page-top"
          li
            a.page-scroll href="#about"  GIỚI THIỆU
          li
            a.page-scroll href="#skills"  KINH NGHIỆM
          li
            a.page-scroll href="#portfolio"  DỊCH VỤ
          li
            a.page-scroll href="#partners"  ĐỐI TÁC
          li
            a.page-scroll href="#contact"  LIÊN HỆ
          li
            - if current_user
              /! Header Navigation Right
              ul.nav-header.pull-right
                li
                  .btn-group
                    button.btn.btn-default.btn-image.dropdown-toggle data-toggle="dropdown" type="button"
                      = image_tag(current_user.avatar.url, class: "user_avatar", size: '30x30', alt: t("common.avatar"))
                      span.caret

                    ul.dropdown-menu.dropdown-menu-right
                      li.dropdown-header
                        = t('.profile')
                      li
                        = link_to edit_profile_users_path, tabindex: -1
                          i.si.si-user.pull-right
                          span.badge.badge-success.pull-right
                          = t('.profile')
                      / li
                      /   = link_to user_notifications_path(current_user), tabindex: -1
                      /     i.si.si-settings.pull-right
                      /     = t('.notifications')
                      li.divider
                      li.dropdown-header
                        =t('.actions')
                      li
                        = link_to  destroy_user_session_path, method: :delete ,tabindex: -1
                          i.si.si-logout.pull-right
                          = t(".logout")
            - else
              = link_to  new_user_session_path, method: :delete ,tabindex: -1
                = t(".login")

app/views/home/_partners.html.slim
/! Achievements Section
#partners.text-center
  .container
    .section-title.center
      h2 ĐỐI TÁC
      h4 MiHa rất vinh dự khi được đồng hành và phát triển cùng với các thương hiệu của đối tác và khách hàng
      hr/
    - row_number = 1
    - col_number = 1
    - 4.times do
      .row
        - 4.times do
          .col-md-3.col-sm-3
            = image_tag "logo/logo_#{col_number}.png",  size: "200x200", class: "img-responsive"

          - col_number += 1
        - row_number += 1

app/views/home/_portfolio.html.slim
#portfolio
  .container
    .section-title.text-center.center
      h2 DỊCH VỤ
      hr
    .categories
      ul.cat
        li
          ol.type
            li
              a.active data-filter="*" href="#"  All
            li
              a data-filter=".camera" href="#"  Camera Solutions
            li
              a data-filter=".web" href="#"  Web Design
            li
              a data-filter=".network" href="#"  Network
            li
              a data-filter=".security" href="#"  Security Solutions
      .clearfix
    .row
      .portfolio-items
        - portfolios.each do |portfolio|
          .col-sm-6.col-md-3.col-lg-3 class="#{portfolio.catgory}"
            .portfolio-item
              .hover-bg
                = link_to "#{asset_path('portfolio/camera-giam-sat-nha-rieng.jpg')}", rel: ("prettyPhoto")
                  .hover-text
                    h4 = portfolio.name

                  = image_tag "#{portfolio.small_image.url(:medium)}", class: "img-responsive img-proj", alt: "Project Title"
              .footer
                .category-name
                  = portfolio.catgory
                .btn.btn-primary
                  = link_to download_pdf_home_index_url, class:'btn btn-primary download-details', target: "_blank"
                    p.text-center
                      i.fa.fa-download.text-center
                      | Chi tiết

app/views/home/_skill.html.slim
/! Skills Section
#skills.text-center
  .container
    .section-title.center
      h2 KINH NGHIỆM
      hr
    .row
      .col-md-3.col-sm-6.skill
        span.chart data-percent="100"
          span.percent 100
        h4 CAMERA
      .col-md-3.col-sm-6.skill
        span.chart data-percent="100"
          span.percent 100
        h4 WEBSITE
      .col-md-3.col-sm-6.skill
        span.chart data-percent="100"
          span.percent 100
        h4 NETWORK
      .col-md-3.col-sm-6.skill
        span.chart data-percent="100"
          span.percent 100
        h4 SECURITY

app/views/home/index.html.slim
/! Header
= render "home/banner", banner_images: @banner_images

/! Navigation
= render "home/nav_bar"

/! About Section
= render "home/about"

/! Skills Section
= render "home/skill"

/! Portfolio Section
= render "home/portfolio", portfolios: @portfolios

/! Achievements Section
= render "home/achievements"

/! Experience
= render "home/partners"

/! Contact Section
= render "home/contact"

/ Footer
= render "layouts/footer"